ktor {
  deployment {
    port = 8000
  }
  application {
    modules = [com.qianrenni.bootstrap.ApplicationKt.main]
  }
}

app {
  contentDir = ${CONTENT_DIR}
  staticDir = ${STATIC_DIR}
  env = ${ENV}
  # 数据库配置
  database {
    # 建议将 IP、端口、库名、用户、密码都拆分为环境变量
    mysql-dsn = ${MYSQL_DSN}
  }

  # 缓存配置
  cache {
    redis-url = ${REDIS_URL}
  }
  security {
    # 密钥必须通过环境变量注入,不要硬编码
    secret-key = ${SECRET_KEY}

    access-token-expire = 43200
    refresh-token-expire = 604800
    email-verify-expire = 300
    captcha-expire = 120
    permission-bit-length = 32
  }

  # 邮箱配置
  email {
    smtp-server = ${SMTP_SERVER}
    smtp-port = ${SMTP_PORT}
    account = ${EMAIL_ACCOUNT}
    code = ${EMAIL_CODE}
  }

  # 服务器配置
  server {
    url = ${SERVER_URL}
    allowHost = ${ALLOW_HOST}
  }
}